### ISSUE TITLE
Add a program for password validation in C#

### ISSUE THREAD

**Issue by srishtipatkar** [srishtipatkar/Password-Validation#6]
Problem statement given in readme file

**Comment by Ajay-Raj-S** [comment]
Hello @srishtipatkar , can you please assign this to me.

**Comment by srishtipatkar** [comment]
> Hello @srishtipatkar , can you please assign this to me.

Done

**Comment by Ajay-Raj-S** [comment]
Thank you, working on it already.

**Comment by Ajay-Raj-S** [comment]
Hello @srishtipatkar I have completed this issue and made a pull request [here](https://github.com/srishtipatkar/Password-Validation/pull/15), please review it.
