### ISSUE TITLE
Add a program for password validation in Java

### ISSUE THREAD

**Issue by srishtipatkar** [srishtipatkar/Password-Validation#9]
Problem statement is given in readme file.

**Comment by Vipul-Bajaj** [comment]
Can i work on this?

**Comment by Sylviaan** [comment]
Can I work on this too?

**Comment by srishtipatkar** [comment]
> Can i work on this?

Sure

**Comment by srishtipatkar** [comment]
> Can I work on this too?

Sure

**Comment by Alireza-Sampour** [comment]
@srishtipatkar  Hi, can you open an issue for php?

**Comment by srishtipatkar** [comment]
> @srishtipatkar Hi, can you open an issue for php?

Done
